### PR TITLE
Add functions to read values from pressure sensors.

### PR DESCRIPTION
**Pull request by generationmake**
add valves function to aux controller

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @generationmake ☕ 👋 

What's the current to voltage conversion circuit looking alike? Since 4 mA are 0 bar and 20 mA are 25 bar the aux controller could be directly publishing Cyphal [DSDL](https://github.com/OpenCyphal/public_regulated_data_types/blob/master/uavcan/si/unit/pressure/Scalar.1.0.dsdl)  pressure values.

**Comment by generationmake** [comment]
Hi @aentinger 
I will go for a 150 ohm resistor.

Any idea how to handle the invalid valid values (below 4 mA) and mark these results as invalid?

**Comment by aentinger** [comment]
No idea. Are you talking about a single in series resistor in the ground path or some kind of differential amplifier?

**Comment by generationmake** [comment]
Hi @aentinger 
just with a single shunt resistor. Like this schematic.

And I suggest to use negative values for invalid measurements.

schematic_valve

**Comment by aentinger** [comment]
Suits me 👍

**Comment by aentinger** [comment]
Closing this PR, as its functionality has been extracted into a separate firmware/repository: https://github.com/107-systems/l3xz-pressure-sensor-firmware .

**Pull request closed without merging**
