### PR TITLE
generate default configuration

### PR DESCRIPTION
**Pull request by generationmake**
according to specification

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger 
according to spec the default node-id is 65535. however its type is unsigned char, so not possible.
could you please check this?
Thanks

**Comment by aentinger** [comment]
I'd go with
```C++
#define CANARD_NODE_ID_MAX 127U
```
as defined in canard.h.

@pavel-kirienko any comment?

**Comment by generationmake** [comment]
see https://opencyphal.org/specification/Cyphal_Specification.pdf#subsection.6.8.1
```
REGISTER NAME PATTERN TYPE FLAGS RECOMMENDED DEFAULT
110 # =====================================================================================================================
111 #
112 # uavcan.node.id natural16[1] mutable, persistent 65535 (unset/PnP)
113 #
114 # Contains the node-ID of the local node. Values above the maximum valid node-ID for the current transport
115 # indicate that the node-ID is not set; if plug-and-play is supported, it will be used by the node to obtain an
116 # automatic node-ID. Invalid values other than 65535 should be avoided for consistency.
```

**Comment by pavel-kirienko** [comment]
If the objective is to assign an invalid node-ID by default, then it should be 65535 as suggested by @generationmake. 127 is not a good choice because it is likely to cause conflicts.

**Comment by aentinger** [comment]
The problem here is that `libcanard` defines `CanardNodeId` to be `uint8_t` (see [here](https://github.com/107-systems/107-Arduino-Cyphal/blob/main/src/libcanard/canard.h#L140)). **65535** won't fly.

**Comment by pavel-kirienko** [comment]
Ah yes indeed. 255 then

**Comment by generationmake** [comment]
the spec defines uavcan.node.id to be natural16.
How about this?

**Comment by pavel-kirienko** [comment]
The data type used for exposing a register value does not necessarily have to match the data type used internally. There may be a variable of type `uint16_t` that stores the node-ID which is cast to `uint8_t` upon use unless it exceeds the range of uint8

**Comment by aentinger** [comment]
Gentleman, I believe I may have found a compromise: ae9144b7dd7b7db219693dc3e3d97a1f1d6eb344  .

@pavel-kirienko @generationmake what do you think?

Note: Plug-And-Play node ID allocation support (via unique IDs) via 107-Arduino-Cyphal is not a priority for me right now. At best I take a well written feature request and I may consider looking into it past ENRICH 23.

**Review by pavel-kirienko — APPROVED** [review]

**Pull request merged**
